#!/bin/sh
set -eu

#            /$$ /$$                   /$$
#           | $$|__/                  | $$
#   /$$$$$$$| $$ /$$          /$$$$$$$| $$$$$$$
#  /$$_____/| $$| $$ /$$$$$$ /$$_____/| $$__  $$
# | $$      | $$| $$|______/|  $$$$$$ | $$  \ $$
# | $$      | $$| $$         \____  $$| $$  | $$
# |  $$$$$$$| $$| $$         /$$$$$$$/| $$  | $$
#  \_______/|__/|__/        |_______/ |__/  |__/
#
#  A minimal, customizable CLI written in shell
#              cli-sh.dev | v0.4.0

# Display available commands, if no command is given
if [ -z "${1:-}" ]; then
    find run -type f

    exit 2
fi

# Run script before command, if it exists
if [ -f "./run/hooks/before" ]; then
    . ./run/hooks/before
fi

# Run provided command with arguments
if [ -d ${1} ]; then
    # When the command is a directory, run script with same name inside it
    "${1}/$(basename ${1})" $(shift; echo ${@})
else
    "${@}"
fi

# Run script after command, if it exists
if [ -f "./run/hooks/after" ]; then
    . ./run/hooks/after
fi
